### Create Order
POST http://localhost:3001/create-order
Content-Type: application/json

{
    "name": "Order 1",
    "product": "Product 1",
    "price": 100,
    "quantity": 1
}


### Create Order with API Gateway
POST http://localhost:3000/orders
Content-Type: application/json

{
    "name": "Order 1",
    "product": "Product 1",
    "price": 100,
    "quantity": 1
}


### Get Orders
GET http://localhost:3001/orders

    